name: Actualizar KML

on:
  schedule:
    - cron: '0 0 * * *'  # Esto ejecutará el flujo de trabajo todos los días a la medianoche
  workflow_dispatch:  # Esto permite ejecutar el workflow manualmente

jobs:
  update_kml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configurar Git
      run: |
        git config user.name "jorman-viafara"
        git config user.email "jorman.viafara@bluelinkbpo.com.co"

    - name: Configurar remote URL con token
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Descargar el archivo KML
      run: |
        curl -L -o puntos_venta_record.kml "https://www.google.com/maps/d/u/0/kml?forcekml=1&mid=1NLx1CntjAmbgd7YzC11IKVSYmOzvaxg"
        echo "Código de respuesta HTTP: $?"  # Muestra el código de respuesta HTTP

    - name: Verificar el contenido del archivo KML
      run: |
        cat puntos_venta_record.kml  # Muestra el contenido del archivo KML descargado

    - name: Subir el archivo KML actualizado (solo si hay cambios)
      run: |
        git add puntos_venta_record.kml
        if git diff --cached --quiet; then
          echo "No hay cambios en el archivo KML, no se hace commit."
        else
          git commit -m "Actualizar archivo KML"
          git push origin main
        fi

